export const BREAKING_CHANGES = 'BREAKING_CHANGES'
export const NO_VERSION_BUMP = 'NO_VERSION_BUMP'
export const INVALID_VERSION_BUMP = 'INVALID_VERSION_BUMP'
export const SPEC_DELETED = 'SPEC_DELETED'
