openapi: "3.0.2"

info:
  title: Accelerator - Order Reference Domain Implementation
  description: Reference domain implementation for Order Service.
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: "1.0"


servers:
  - url: /api/v1


paths:

  /customer-orders:
    get:
      tags:
        - CustomerOrder
      summary: List all customer order information.
      description: List details of all customer orders.
      operationId: listOrder

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListCustomerOrderResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
    post:
      tags:
        - CustomerOrder
      summary: Create new customer order.
      description: Create new customer order.
      operationId: createOrder

      requestBody:
        description: Place new order.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCustomerOrderRequest'
        required: true

      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCustomerOrderResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /customer-orders/{id}:
    get:
      tags:
        - CustomerOrder
      summary: Retrieve details of a particular customer order.
      description: Get customer order detail by customer order ID.
      operationId: getOrder
      parameters:
        - name: id
          in: path
          description: Customer order ID.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCustomerOrderResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: Order is not found

security:
  - basicAuth: []

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

  schemas:
    CustomerOrderResponse:
      required:
        - orderNumber
        - customerId
        - grandTotal
        - subTotal
      type: object

      properties:
        id:
          type: integer
          format: int64
          example: 1001
        orderNumber:
          type: string
          example: test-order-number-0001
        customerId:
          type: integer
          format: int64
          example: 203
        grandTotal:
          type: number
          example: 123.1
        subTotal:
          type: number
          example: 123.1

    CreateCustomerOrderRequest:
      required:
        - orderNumber
        - customerId
        - grandTotal
      type: object

      properties:
        orderNumber:
          type: string
          example: test-order-number-0001
        customerId:
          type: integer
          format: int64
          example: 203
        grandTotal:
          type: number
          example: 123.1

    GetCustomerOrderResponse:
      required:
        - customerOrder
      type: object
      properties:
        customerOrder:
          type: object
          $ref: '#/components/schemas/CustomerOrderResponse'
    CreateCustomerOrderResponse:
      required:
        - customerOrder
      type: object
      properties:
        customerOrder:
          type: object
          $ref: '#/components/schemas/CustomerOrderResponse'
    ListCustomerOrderResponse:
      required:
        - customerOrders
      type: object
      properties:
        customerOrders:
          type: array
          items:
            $ref: '#/components/schemas/CustomerOrderResponse'

  responses:
    UnauthorizedError:
      description: Authentication information is missing or invalid
      headers:
        Authorization:
          schema:
            type: string
          description: Basic authentication