artifactory:
  name: jfrog
  username: '${{ JFROG_USERNAME }}'
  apiKey: '${{ JFROG_API_KEY }}'
  url: 'https://idigital.jfrog.io/artifactory/contracts-generic-local/openapi'
outputDir: generated
package:
  scope: '@ikigai-digital'
  repoId: 'open-api-demo'
  gitUserId: 'ikigai-digital'
contracts:
  cardsPostingApi:
    type: provider
    boundedContext: cards
    name: cardsPostingApi
    version: 1.0.1
  getWalletsApi:
    type: client
    boundedContext: wallet
    name: getWalletsApi
    version: 1.0.0
