platform:
  name: jfrog
outputDir: generated
contracts:
  cardsPostingApi:
    type: provider
    boundedContext: cards
    name: cardsPostingApi
    version: 1.0.1
  getWalletsApi:
    type: client
    boundedContext: wallet
    name: getWalletsApi
    version: 1.0.0
