name: "Validate changed specs and publish snapshots"

on:
  pull_request:
    branches: []

jobs:
  validate-openapi-specs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: ikigai-digital/setup-openapi-cli-action@v1.0.0
        with:
          auth-token: ${{ secrets.JFROG_NPM_AUTH_TOKEN }}
          auth-email: ${{ secrets.JFROG_NPM_AUTH_EMAIL }}
          registry: ${{ secrets.JFROG_REGISTRY_URL }}
      - name: Validate openapi spec format
        run: openapi validate -d -c openapi/config.yml
      - name: Publish snapshot without validating the bump
        run: openapi publish -d -c openapi/config.yml -snapshot -snapshotBranchName ${{ github.ref_name }}
      - name: Validate openapi changes
        run: openapi validate-version-bump -d -c openapi/config.yml
